default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost
  username: postgres
  password: 222345

development:
  <<: *default
  database: ecommerce_dev

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_prod
